import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-5 py-2 flex  justify-between bg-stone-800 items-center ">
          <img className=" w-[120px] " src="/logo.png" alt="" />

          <div className="  mx-5">
            <Link className="btn mr-2" href={"/"}>Food </Link>
            <Link className="btn mr-2" href={"/"}>Reviews</Link>
            
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
