import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartProvider from "@/context/CartProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const poppins = Poppins({
  weight: ["400", "300", "200"],
  subsets:["latin"]
});

export const metadata = {
  title:{
    default:"Yantun khaijan",
    template:"%s | Yantun khaijan",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <header className="px-5 py-2 flex  sticky justify-between bg-stone-800 items-center ">
          <Link href={"/"}>
            {" "}
            <img className=" w-[120px] " src="/logo.png" alt="" />
          </Link>

          <div className="  mx-5">
            <Link className="btn mr-2" href={"/foods"}>
              Food{" "}
            </Link>
            <Link className="btn mr-2" href={"/reviews"}>
              Reviews
            </Link>
            <Link className="btn mr-2" href={"/feedbacks"}>
             Feedback
            </Link>
          </div>
        </header>

        <main className=" max-w-7xl mx-auto py-8">
          <CartProvider>{children}</CartProvider>
        </main>
      </body>
    </html>
  );
}
